# Figure 1: the evidence-to-claim architecture.
#
# Drawn in R so the figure is regenerated by the same pipeline as every other
# display item. The layout is declared as data, not hand-placed.

source(file.path("M2.3", "analysis", "r", "_theme.R"))

# Adjacent boxes in a row sit 1.6 apart, so the width leaves a visible surface
# gap rather than merging three boxes into one bar.
BOX_W <- 1.44
BOX_H <- 0.62

nodes <- tibble::tribble(
  ~id,        ~x,   ~y,   ~label,                              ~stage,
  "obs",      1,    5.6,  "Observations\nheads, tracers, chemistry", "Input",
  "cand",     1,    4.4,  "Candidate generation\nedges, ages, families", "Evidence",
  "age",      -0.6, 3.1,  "Age\nspecialist",                   "Evidence",
  "rx",       1,    3.1,  "Reaction\nspecialist (RAPM)",       "Evidence",
  "kin",      2.6,  3.1,  "Kinetic\nadapter",                  "Evidence",
  "cal",      1,    1.9,  "Calibration\nintervals, selective risk", "Control",
  "disc",     1,    0.75, "Discrepancy and\nmodel averaging",  "Control",
  "gate",     1,    -0.5, "Claim gate",                        "Decision",
  "pass",     -0.6, -1.8, "PASS\nprovenance-linked report",    "Outcome",
  "weak",     1,    -1.8, "WEAK\nreported below floor",        "Outcome",
  "abst",     2.6,  -1.8, "ABSTAIN\nnext-measurement record",  "Outcome"
)

edges <- tibble::tribble(
  ~from,   ~to,
  "obs",   "cand",
  "cand",  "age",
  "cand",  "rx",
  "cand",  "kin",
  "age",   "cal",
  "rx",    "cal",
  "kin",   "cal",
  "cal",   "disc",
  "disc",  "gate",
  "gate",  "pass",
  "gate",  "weak",
  "gate",  "abst"
)

seg <- edges |>
  left_join(nodes |> select(id, x, y), by = c("from" = "id")) |>
  rename(x0 = x, y0 = y) |>
  left_join(nodes |> select(id, x, y), by = c("to" = "id")) |>
  rename(x1 = x, y1 = y) |>
  # Trim each connector to the box edges so no arrow head sits under a label.
  mutate(dy = sign(y1 - y0),
         y0 = y0 + dy * BOX_H / 2,
         y1 = y1 - dy * BOX_H / 2)

STAGE_FILL <- c(Input = "#E8EEF4", Evidence = "#D6E4F0", Control = "#CFE4DC",
                Decision = "#F6E3CB", Outcome = "#EDEFF1")
STAGE_LINE <- c(Input = "#7A8B99", Evidence = PAL[1], Control = PAL[3],
                Decision = PAL[5], Outcome = "#8A9199")

nodes <- nodes |>
  mutate(stage = factor(stage, levels = names(STAGE_FILL)))

fig <- ggplot() +
  geom_segment(data = seg, aes(x = x0, y = y0, xend = x1, yend = y1),
               colour = "#8A9199", linewidth = 0.35,
               arrow = arrow(length = unit(1.5, "mm"), type = "closed")) +
  geom_tile(data = nodes, aes(x, y, fill = stage, colour = stage),
            width = BOX_W, height = BOX_H, linewidth = 0.45) +
  geom_text(data = nodes, aes(x, y, label = label), size = 2.05,
            colour = INK, lineheight = 1.05) +
  scale_fill_manual(values = STAGE_FILL, name = NULL) +
  scale_colour_manual(values = STAGE_LINE, guide = "none") +
  annotate("text", x = 3.95, y = 4.4, hjust = 0, size = 2.0, colour = INK_MUTED,
           label = "Candidate sets are retained,\nnot collapsed to one path") +
  annotate("text", x = 3.95, y = 1.9, hjust = 0, size = 2.0, colour = INK_MUTED,
           label = "Calibration is fitted on\ndevelopment cases only") +
  annotate("text", x = 3.95, y = -0.5, hjust = 0, size = 2.0, colour = INK_MUTED,
           label = "Locked cases are scored\nafter prediction") +
  coord_cartesian(xlim = c(-1.8, 6.6), ylim = c(-2.4, 6.1)) +
  guides(fill = guide_legend(nrow = 1, override.aes = list(colour = NA))) +
  labs(title = "Evidence-to-claim architecture") +
  theme_void(base_size = 9) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0,
                                  margin = margin(b = 4)),
        legend.position = "bottom", legend.text = element_text(size = 6.5),
        legend.key.size = unit(0.30, "cm"),
        plot.background = element_rect(fill = "white", colour = NA),
        plot.margin = margin(5, 5, 4, 5))

save_fig(fig, "FIG-1_architecture", width_mm = 140, height_mm = 118)
