"""
Nuclear tracer module for groundwater age dating and flow inference.
"""

from .nuclides import Nuclide, TRITIUM, CARBON14, KRYPTON85, get_nuclide
from .input_history import InputHistory, load_input_series_csv, build_default_tritium_input, get_input_history
from .lpm import convolve_input, piston_flow_model, exponential_model
from .invert import infer_age_from_tracer
from .multi_tracer import (
    TracerAgeEstimate,
    build_atmospheric_tracer_input,
    combine_tracer_age_estimates,
    infer_3h_3he_age,
    infer_atmospheric_tracer_age,
    infer_helium4_accumulation_age,
    infer_multi_tracer_age,
)
from .joint_lpm import (
    JointLpmFit,
    SUPPORTED_LPM_MODELS,
    TracerFitObservation,
    TracerFitResidual,
    build_lpm_tracer_observations,
    fit_lpm_model,
    fit_lpm_models,
    predict_lpm_tracers,
    tracer_response_kernel,
    transit_time_pdf,
)
from .ttd_identified import (
    AgeFunctional,
    IdentifiedBound,
    TracerConstraint,
    TtdEvidenceReport,
    assess_held_out_tracer,
    bound_linear_functional,
    build_tracer_constraints,
    build_tracer_response_matrix,
    infer_ttd_evidence,
    predict_tracer_bounds,
    solve_ttd_identified_set,
    standard_age_functionals,
)
from .ttd_design import (
    CandidateTracerMeasurement,
    TracerDesignScenario,
    TtdHypothesisEnsemble,
    build_ttd_measurement_options,
    rank_ttd_measurements,
    select_ttd_measurement_batch,
)
from .ttd_graph import (
    GraphCompatibilityAudit,
    MassTransportMap,
    audit_ttd_graph_compatibility,
)
from .dissolved_gas import (
    DissolvedGasFit,
    DissolvedGasObservation,
    DissolvedGasResidual,
    atmospheric_equivalent_from_dissolved,
    build_dissolved_gas_observations,
    correct_environmental_tracers,
    equilibrium_concentration_ccstp_g,
    excess_air_concentration_ccstp_g,
    fit_and_correct_dissolved_gases,
    fit_dissolved_gas_model,
    mg_l_from_ccstp_g,
    monte_carlo_dissolved_gas_fit,
    predict_dissolved_gas_ccstp_g,
    pressure_from_elevation_atm,
    to_ccstp_g,
    water_vapor_pressure_atm,
)
from .tracer_inputs import (
    GAS_TRACERS,
    dissolved_gas_to_atmospheric_equivalent,
    load_tracer_histories,
    load_tracer_histories_csv,
    normalize_tracer_key,
    standardize_gas_observations,
)
from .diagnostics import (
    diagnose_lpm_identifiability,
    diagnose_tracer_disagreement,
    tracer_removal_sensitivity,
)
from .age_coherence import audit_graph_age_coherence

__all__ = [
    "Nuclide",
    "TRITIUM",
    "CARBON14",
    "KRYPTON85",
    "get_nuclide",
    "InputHistory",
    "load_input_series_csv",
    "build_default_tritium_input",
    "get_input_history",
    "convolve_input",
    "piston_flow_model",
    "exponential_model",
    "infer_age_from_tracer",
    "TracerAgeEstimate",
    "build_atmospheric_tracer_input",
    "combine_tracer_age_estimates",
    "infer_3h_3he_age",
    "infer_atmospheric_tracer_age",
    "infer_helium4_accumulation_age",
    "infer_multi_tracer_age",
    "JointLpmFit",
    "SUPPORTED_LPM_MODELS",
    "TracerFitObservation",
    "TracerFitResidual",
    "build_lpm_tracer_observations",
    "fit_lpm_model",
    "fit_lpm_models",
    "predict_lpm_tracers",
    "tracer_response_kernel",
    "transit_time_pdf",
    "AgeFunctional",
    "IdentifiedBound",
    "TracerConstraint",
    "TtdEvidenceReport",
    "assess_held_out_tracer",
    "bound_linear_functional",
    "build_tracer_constraints",
    "build_tracer_response_matrix",
    "infer_ttd_evidence",
    "predict_tracer_bounds",
    "solve_ttd_identified_set",
    "standard_age_functionals",
    "CandidateTracerMeasurement",
    "TracerDesignScenario",
    "TtdHypothesisEnsemble",
    "build_ttd_measurement_options",
    "rank_ttd_measurements",
    "select_ttd_measurement_batch",
    "GraphCompatibilityAudit",
    "MassTransportMap",
    "audit_ttd_graph_compatibility",
    "DissolvedGasFit",
    "DissolvedGasObservation",
    "DissolvedGasResidual",
    "atmospheric_equivalent_from_dissolved",
    "build_dissolved_gas_observations",
    "correct_environmental_tracers",
    "equilibrium_concentration_ccstp_g",
    "excess_air_concentration_ccstp_g",
    "fit_and_correct_dissolved_gases",
    "fit_dissolved_gas_model",
    "mg_l_from_ccstp_g",
    "monte_carlo_dissolved_gas_fit",
    "predict_dissolved_gas_ccstp_g",
    "pressure_from_elevation_atm",
    "to_ccstp_g",
    "water_vapor_pressure_atm",
    "GAS_TRACERS",
    "dissolved_gas_to_atmospheric_equivalent",
    "load_tracer_histories",
    "load_tracer_histories_csv",
    "normalize_tracer_key",
    "standardize_gas_observations",
    "diagnose_lpm_identifiability",
    "diagnose_tracer_disagreement",
    "tracer_removal_sensitivity",
    "audit_graph_age_coherence",
]
